---
title: "R Notebook"
output: html_notebook
---

```{r}
library(SummarizedExperiment)
```



```{r}
kd6 <- readRDS("../../../data/prmt-apa/kd6_essential_bulk_expressed.Rds")
rowData(kd6)
colData(kd6)
kd6
```


1. Our sites of interest
```{r}
# Define the folder path
folder_path <- "../motif_and_clip_analysis/DMAi_vs_non_DMAi/bed"

# Get the list of files in the folder
files <- list.files(path = folder_path, pattern = "\\.bed$", full.names = TRUE)

df_list <- list()

# Loop through each file
for (file in files) {
  # Read the file into a dataframe
  df <- read.table(file, header = FALSE, sep = "\t", stringsAsFactors = FALSE)
  
  # Extract the filename without the path
  file_name <- basename(file)
  
  # Add the "condition" column
  df$condition <- sapply(file_name, function(file_name) {
    if (grepl("non_DMAi", file_name)) {
      case <- "non_DMAi"
    } else if (grepl("DMAi", file_name)) {
      case <- "DMAi"
    } else if (grepl("control", file_name)) {
      case <- "control"
    } else {
      case <- "siCFIM25"
    }
    
    switch(case,
      "non_DMAi" = "nonDMAi",
      "DMAi" = "DMAi",
      "control" = "control",
      "siCFIM25"  # Default case
    )
  })
  
  # Add the "site_type" column
  if (grepl("distal", file_name)) {
    df$site_type <- "distal"
  } else if (grepl("proximal", file_name)) {
    df$site_type <- "proximal"
  }
  
  # Convert the dataframe to a GRanges object
  gr <- GRanges(seqnames = Rle(df$V1),
                ranges = IRanges(start = df$V2, end = df$V3),
                strand = Rle(df$V6),
                name = df$V4,
                condition = df$condition,
                site_type = df$site_type)
  # These are 400nt ranges with 200nt flanking the polyA site on either side, lets make them 20nt ranges with 10nt either side for matching with the other dataset ( i tried 4nt range and 10nt range - 4->10 gives you more, 10->20 is a couple more but not that many)
  gr <- resize(gr, width = 20, fix = "center")
  df_list[[file_name]] <- gr
}

df_list
```

2. now to address the quantified perturb-seq sites
the intervals i think are in the annotations provided by another file

```{r}
annot = readRDS("../../../data/prmt-apa/utrome_hg38_v1_gene_annots.2024.05.13.Rds")
annot
```

