---
title: "Untitled"
output: html_document
date: "2025-05-14"
---

```{r setup, include=FALSE}

```



```{r cars}
alltrag = fread("../data/all_96hrs_GO_groups_with_LFC_and_APA.csv")
alltrag %>% filter(pA_type=="proximal pA" & grepl("up",APA_and_gene_class_96hrs) & prox_to_dist_shift_24hrs > 0.2 & log2FoldChange_24hrs < 0.1) %>%
  select(-feature_id,-chr,-strand,-pA_type,-start,-end) %>%
  melt() %>%
  extract(variable, into = c("metric", "timepoint"), regex = "(.+?)_(\\d+hrs)", remove = TRUE) %>%
  select(gene_name) %>% unique()
  
  %>%
  ggplot(.,aes(x=timepoint,y=value,group=gene_name,colour=APA_and_gene_class_96hrs)) + geom_line() + facet_wrap(~metric+APA_and_gene_class_96hrs,scales="free_y") + theme_few()+
  expand_limits(y = 0) +
  ggtitle("E2F1 trajectory")
```



```{r pressure, echo=FALSE}
alltrag %>% filter(pA_type=="proximal pA" & gene_name=="HNRNPA0") %>%
  select(-feature_id,-chr,-strand,-pA_type,-start,-APA_and_gene_class_96hrs, -end) %>%
  melt() %>%
  extract(variable, into = c("metric", "timepoint"), regex = "(.+?)_(\\d+hrs)", remove = TRUE) %>%
  ggplot(.,aes(x=timepoint,y=value,group=gene_name,colour=)) + geom_line() + facet_wrap(~metric,scales="free_y") + theme_few()+
  expand_limits(y = 0) +
  ggtitle("hnRNPA0 trajectory")
```


